version: '3.8'

services:
  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8062:8062"
  #   volumes:
  #     - ./api:/app
  #   networks:
  #     - app-network
  #   restart: unless-stopped

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8063:8063"
  #   depends_on:
  #     - api
  #   volumes:
  #     - ./frontend:/app
  #   networks:
  #     - app-network
  #   restart: unless-stopped

  pipeline:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    networks:
      - app-network
    restart: unless-stopped
    command: ["python", "01_data_feeder.py"]
    # command: ["python", "01_data_feeder.py", "&&", "python", "02_data_preprocessing.py"]


networks:
  app-network:
    driver: bridge
